export const SET_CUSTOMER = 'SET_CUSTOMER';
export const SET_CUSTOMER_DELETE = 'SET_CUSTOMER_DELETE';
export const SET_SHOP = 'SET_SHOP';
export const SET_SHOP_DELETE = 'SET_SHOP_DELETE';
export const SET_FILTER = 'SET_FILTER';
export const SET_FILTER_DELETE = 'SET_FILTER_DELETE';
export const SET_SEARCH_FLAG = 'SET_SEARCH_FLAG';
export const SET_MESSAGES_COUNT = 'SET_MESSAGES_COUNT';
